name: 'Build Chrome extension'
on:
  push:
    branches:
      - main
jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |-
          npm run build

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: darkreader-chrome
          path: build/release/darkreader-chrome.zip
