name: 'Build Chrome extension'
on:
  push:
    branches:
      - main
jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build zip file
        run: npm run build

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: darkreader-chrome
          path: build/release/darkreader-chrome.zip
