name: 'Build Chrome extension'
on:
  push:
    branches:
      - main
jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      - name: Install NPM dependencies
        run: npm ci

      - name: Build zip file
        run: npm run build

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: darkreader-chrome
          path: build/release/darkreader-chrome.zip
